### ISSUE TITLE
Unable to locate @angular/forms

### ISSUE THREAD

**Issue by rileymckenna** [areijngoudt/swagger-ts-generator#11]
I am new to TS and i am trying to use your product to generate models for my TS app. Worked perfectly, thank you! I am not sure why, but the 
```import { Validators, FormControl, FormGroup, FormArray, ValidatorFn } from "@angular/forms";```
Cannot find ```@angular/forms```. I looked through the dependencies in package.json and i dont see dependency on it. I was a little confused on where to go from here.

**Comment by areijngoudt** [comment]
Hi Riley,

You need to add this dependency in package.json:

"@angular/forms": "^6.1.8",

or whatever version you are using.

Best regards,
Ad

Op do 15 nov. 2018 om 19:13 schreef Riley McKenna <notifications@github.com
