### ISSUE TITLE
subTypePropertyName not implementing type

### ISSUE THREAD

**Issue by a90machado** [areijngoudt/swagger-ts-generator#12]
Hi there, iam implementing swagger-ts-generator, every thing does well, but the subTypePropertyName does add the type in models, generate an error because this sub type is not declared;

I have to add this line (typeSelector: string; // ADDED LINE) too all my files that implement typeSelector.

This make my server not automated. Can you help me with this?

**Comment by a90machado** [comment]
I have change to Swagger CodeGen. Thanks same way.

**Comment by areijngoudt** [comment]
Hi Machado,

Ok.

Succes using the tool!

Best regards,
Ad

Op ma 18 mrt. 2019 om 18:28 schreef Machado <notifications@github.com>:
