### ISSUE TITLE
High level vulnerability in one of dependencies

### ISSUE THREAD

**Issue by SkrzypMajster** [areijngoudt/swagger-ts-generator#13]
Hi,

I'm using swagger-ts-generator in one of my projects.
I recently noticed that one of swagger-ts-generator dependencies has high level security vulnerability.

When I ran **npm audit** command I found that **handlebars** package in versions lower than 4.0.14 has vulnerability called "Prototype Pollution".

For more informations, you can check link below:
https://www.npmjs.com/advisories/755

I would be very grateful for updating this package, which removes the message about security vulnerabilities.

**Comment by areijngoudt** [comment]
I've updated to handlebars 4.5.1
