### ISSUE TITLE
is it possible  to use swagger-ts-generator to generate models without angular dependencies

### ISSUE THREAD

**Issue by jayalakshmis** [areijngoudt/swagger-ts-generator#3]
Hello,
First of all, I would like to appreciate the effort on this library. Thank you! I was wondering if it is possible to use this library to generate ts models without any angular imports? My intention is to simply use the generated models on my vuejs project to cast any response from the api to the models.
Is it right to assume that i would have to modify the the handle bar files `.hbs` files to get rid of the angular imports?

**Comment by areijngoudt** [comment]
Hi Jaya,

You could make a fork at alter the Handlebar templates in the templates
folder to your needs.

Happy coding,
Ad

2018-03-13 19:12 GMT+01:00 Jaya <notifications@github.com>:
